/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.pftqg.android.JustTwitter;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int borderedbox=0x7f020000;
        public static final int gradient_dark_gray=0x7f020001;
        public static final int gradient_gray=0x7f020002;
        public static final int ic_menu_camera=0x7f020003;
        public static final int ic_menu_delete=0x7f020004;
        public static final int ic_menu_edit=0x7f020005;
        public static final int ic_menu_help=0x7f020006;
        public static final int ic_menu_info_details=0x7f020007;
        public static final int ic_menu_preferences=0x7f020008;
        public static final int ic_menu_revert=0x7f020009;
        public static final int ic_menu_search=0x7f02000a;
        public static final int ic_menu_send=0x7f02000b;
        public static final int ic_menu_view=0x7f02000c;
        public static final int icon=0x7f02000d;
        public static final int placeholder=0x7f02000e;
        public static final int stat_notify_chat=0x7f02000f;
        public static final int sym_action_chat=0x7f020010;
        public static final int sym_action_email=0x7f020011;
    }
    public static final class id {
        public static final int aboutmessage=0x7f060011;
        public static final int avatar=0x7f06000e;
        public static final int directmessages=0x7f060006;
        public static final int loginInitiateLogin=0x7f060003;
        public static final int loginPassword=0x7f060002;
        public static final int loginUsername=0x7f060001;
        public static final int mentions=0x7f060005;
        public static final int message=0x7f060010;
        public static final int newTweetAccessoryView=0x7f06000c;
        public static final int newTweetCancel=0x7f060008;
        public static final int newTweetMessage=0x7f060009;
        public static final int newTweetPost=0x7f06000a;
        public static final int newTweetRemainingCount=0x7f06000d;
        public static final int newTweetText=0x7f06000b;
        public static final int newTweetTopBar=0x7f060007;
        public static final int timeline=0x7f060004;
        public static final int tweetViewAvatar=0x7f060013;
        public static final int tweetViewInReplyTo=0x7f06001a;
        public static final int tweetViewInfoBar=0x7f060012;
        public static final int tweetViewInfoButton=0x7f060016;
        public static final int tweetViewMakeFavourite=0x7f06001f;
        public static final int tweetViewRealName=0x7f060014;
        public static final int tweetViewReply=0x7f06001d;
        public static final int tweetViewRetweet=0x7f060020;
        public static final int tweetViewScreenName=0x7f060015;
        public static final int tweetViewSendDM=0x7f06001e;
        public static final int tweetViewToolbar=0x7f06001c;
        public static final int tweetViewTweetContents=0x7f060017;
        public static final int tweetViewTweetSource=0x7f060019;
        public static final int tweetViewTweetTime=0x7f060018;
        public static final int tweetViewWasInReplyTo=0x7f06001b;
        public static final int username=0x7f06000f;
        public static final int widget30=0x7f060000;
    }
    public static final class layout {
        public static final int login_window=0x7f030000;
        public static final int main=0x7f030001;
        public static final int newtweet=0x7f030002;
        public static final int tweet=0x7f030003;
        public static final int tweetview=0x7f030004;
    }
    public static final class string {
        public static final int activity_composer=0x7f050002;
        public static final int activity_login=0x7f050004;
        public static final int activity_preferences=0x7f050005;
        public static final int activity_viewer=0x7f050003;
        public static final int app_name=0x7f050001;
        public static final int exception=0x7f05000a;
        public static final int hello=0x7f050000;
        public static final int menu_post=0x7f050006;
        public static final int menu_refresh=0x7f050007;
        public static final int menu_settings=0x7f050008;
        public static final int menu_viewed=0x7f050009;
        public static final int ok=0x7f05000b;
    }
    public static final class xml {
        public static final int preferences=0x7f040000;
    }
}
